apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-daemonset
spec:
  selector:
    matchLabels:
      name: nvidia-driver-ds
  template:
    metadata:
      labels:
        name: nvidia-driver-ds
    spec:
      hostPID: true
      
      nodeSelector:
        driver-type: container
        server-type: render
      
      containers:
      - image: nvidia/driver:418.87.01-ubuntu16.04
        name: nvidia-driver
        args: ["--accept-license"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: update-driver
          mountPath: /run/kernel/postinst.d
        - name: driver-path
          mountPropagation: Bidirectional
          mountPath: /run/nvidia

      volumes:
      - name: update-driver
        hostPath:
          path: /etc/kernel/postinst.d
      - name: driver-path
        hostPath:
          path: /run/nvidia

